# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""


from openapi_client.components.request_bodies import request_body_user_array
RequestBody = request_body_user_array.UserArray
