# coding: utf-8

"""
    OpenAPI Petstore
    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501
    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""


from openapi_client.components.schema import api_response
Schema = api_response.ApiResponse
