# coding: utf-8

"""
    OpenAPI Petstore
    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.  # noqa: E501
    The version of the OpenAPI document: 1.0.0
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.shared_imports.schema_imports import *


class Schema(
    schemas.Int64Schema
):


    class Schema_:
        types = {
            decimal.Decimal,
        }
        format = 'int64'
        inclusive_maximum = 5
        inclusive_minimum = 1
