# coding: utf-8
"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.shared_imports.server_imports import *


@dataclasses.dataclass
class Server0(server.Server):
    _url: str = "http://petstore.swagger.io/v2"
