# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.store_order_order_id.delete.operation import DeleteOrder
from openapi_client.paths.store_order_order_id.get.operation import GetOrderById
from openapi_client.paths.store_inventory.get.operation import GetInventory
from openapi_client.paths.store_order.post.operation import PlaceOrder


class StoreApi(
    DeleteOrder,
    GetOrderById,
    GetInventory,
    PlaceOrder,
):
    """NOTE: This class is auto generated by OpenAPI JSON Schema Generator
    Ref: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator

    Do not edit the class manually.
    """
    pass
