# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import dataclasses
import typing
import typing_extensions

from openapi_client import security_schemes

@dataclasses.dataclass
class ApiKey(security_schemes.ApiKeySecurityScheme):
    name: str = "api_key"
    in_location: security_schemes.ApiKeyInLocation = security_schemes.ApiKeyInLocation.HEADER
