# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

import dataclasses
import datetime
import decimal
import io
import typing
import uuid

import frozendict
import typing_extensions
import urllib3

from openapi_client import api_client
from openapi_client import schemas


@dataclasses.dataclass
class ApiDefault(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: schemas.Unset = schemas.unset
    headers: schemas.Unset = schemas.unset


class Default(api_client.OpenApiResponse[ApiDefault]):
    response_cls = ApiDefault
