# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.pet.post.operation import ApiForPost
from openapi_client.paths.pet.put.operation import ApiForPut


class Pet(
    ApiForPost,
    ApiForPut,
):
    pass
