# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.pet_pet_id.delete.operation import ApiForDelete
from openapi_client.paths.pet_pet_id.get.operation import ApiForGet
from openapi_client.paths.pet_pet_id.post.operation import ApiForPost


class PetPetId(
    ApiForDelete,
    ApiForGet,
    ApiForPost,
):
    pass
