# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.pet_find_by_status.get.operation import ApiForGet


class PetFindByStatus(
    ApiForGet,
):
    pass
