# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.pet_pet_id_upload_image.post.operation import ApiForPost


class PetPetIdUploadImage(
    ApiForPost,
):
    pass
