# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.store_inventory.get.operation import ApiForGet


class StoreInventory(
    ApiForGet,
):
    pass
