# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.store_order_order_id.delete.operation import ApiForDelete
from openapi_client.paths.store_order_order_id.get.operation import ApiForGet


class StoreOrderOrderId(
    ApiForDelete,
    ApiForGet,
):
    pass
