# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.user_create_with_array.post.operation import ApiForPost


class UserCreateWithArray(
    ApiForPost,
):
    pass
