# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.user.post.operation import ApiForPost


class User(
    ApiForPost,
):
    pass
