# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.user_username.delete.operation import ApiForDelete
from openapi_client.paths.user_username.get.operation import ApiForGet
from openapi_client.paths.user_username.put.operation import ApiForPut


class UserUsername(
    ApiForDelete,
    ApiForGet,
    ApiForPut,
):
    pass
