# coding: utf-8

"""


    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client.paths.user_login.get.operation import ApiForGet


class UserLogin(
    ApiForGet,
):
    pass
