# coding: utf-8

"""
    Generated by: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator
"""

from openapi_client import security_schemes

security_requirement_object: security_schemes.SecurityRequirementObject = {
    "petstore_auth": ("write:pets", "read:pets", ),
}
